package common;


/**
* common/c.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from common.idl
* Tuesday, October 19, 2021 5:20:21 o'clock PM EDT
*/

public interface c extends cOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface c
