package common;

/**
* common/cHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from common.idl
* Tuesday, October 19, 2021 5:20:21 o'clock PM EDT
*/

public final class cHolder implements org.omg.CORBA.portable.Streamable
{
  public common.c value = null;

  public cHolder ()
  {
  }

  public cHolder (common.c initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.cHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.cHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.cHelper.type ();
  }

}
